apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: railsweb
  namespace: railsapp
  labels:
    purpose: webappforrails
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
      - name: webapp
        image: benjamincaldwell/hello-docker-rails
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: shopify
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"

